name       : perl-clone
version    : '0.46'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GARU/Clone-0.46.tar.gz : aadeed5e4c8bd6bbdf68c0dd0066cb513e16ab9e5b4382dc4a0aafd55890697b
homepage   : https://metacpan.org/pod/Clone
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl Clone()
description: |
    This module provides a clone() method which makes recursive copies of nested hash, array, scalar and reference types, including tied variables and objects.

    clone() takes a scalar argument and duplicates it. To duplicate lists, arrays or hashes, pass them in by reference, e.g.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
